### PR TITLE
Bump ci rust toolchain

### PR DESCRIPTION
**Pull request by Nugine**
Related: #17

### CODE REVIEW

**Comment by Nugine** [comment]
Ready to merge

**Comment by Nugine** [comment]
Request review @francis0407 @rogercloud @pzheng1025

**Review by pzheng1025 — APPROVED** [review]

**Comment by pzheng1025** [comment]
Is the clippy change introduced by new Rust version?

**Comment by Nugine** [comment]
> Is the clippy change introduced by new Rust version?

Yes. The CI will be broken every six weeks if we use the stable toolchain.

**Pull request merged**
